### ISSUE TITLE
Ion 1.1 Implementation Roadmap

### ISSUE THREAD

**Issue by toddjonker** [amazon-ion/ion-tests#94]
Master issue tracking work to do across various repositories.

- [ ] Integrate with conformance test suite
    - [ ] Java
    - [ ] Rust
- [ ] `$ion_literal`
    - [ ] Test cases 
    - [ ] Java
    - [ ] Rust
- [ ] System macros `void` and `values`
- [ ] Text Eexp can resolve system macros by local reference `(:void)`
- [ ] Text Eexp can resolve system macros by qualified reference `(:$ion:void)`
- [ ] System macros `make_list` and `make_sexp`
- [ ] System macros `make_string` and `make_symbol`
- [ ] System macro `annotate` (requires `*`
